/**
 * Project EULER
 * Challenge Nº2
 * https://projecteuler.net/problem=2
 *
 * Description:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

function isEven(number: number): boolean {
  return number % 2 === 0;
}

function sum(total: number, number: number): number {
  return total + number;
}

function solve(numbers: number[]): number {
  return numbers.filter(isEven).reduce(sum);
}

export { solve };
